version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            # @todo #1 Включить оценку покрытия (coverage, когда появятся тесты)
            . venv/bin/activate
            # @todo #12 Использовать pdd для контроля паззлов
            pycodestyle . --exclude=./venv/* --ignore=W191
            find node node.test -name *.py | xargs pylint
            pytest -v
