version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            pycodestyle node node.test --ignore=W191
            pylint node node.test
            # @todo #12 Использовать pdd для контроля паззлов
            # @todo #9 Использовать radon для контроля цикломатической сложности и уровня
            #  поддерживаемости.
            # @todo #1 Включить оценку покрытия (coverage, когда появятся тесты)
            pytest -v
