---
- name: Install gunicorn package
  pip:
    name: gunicorn
    executable: pip3
- name: install gunicorn service
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
- name: install gunicorn socket
  copy:
    src: gunicorn.socket
    dest: /etc/systemd/system/
- name: install gunicorn tmpfile
  copy:
    src: gunicorn.conf
    dest: /etc/tmpfiles.d/
- name: create gunicorn socket directory
  file:
    path: /run/gunicorn
    state: directory
- name: Restart gunicorn
  systemd:
    name: gunicorn
    enabled: yes
    state: restarted
