---
- name: Install gunicorn package
  pip:
    name: gunicorn
    executable: pip3
- name: install gunicorn service
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
- name: install gunicorn tmpfile
  copy:
    src: gunicorn.conf
    dest: /etc/tmpfiles.d/
- name: Activate gunicorn
  systemd:
    name: gunicorn
    enabled: yes
    daemon_reload: yes
    state: restarted
# @todo #113 После заливки сервер возвращает 502
#  Если не сделать рестарт сервиса.
#  Причем команда service не дает того же эффекта, что странно.
- name: Restart gunicorn
  become: yes
  shell: |
    service gunicorn stop
    service gunicorn start
