---
- name: Install gunicorn package
  pip:
    name: gunicorn
    executable: pip3
- name: install gunisorn service
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
- name: install gunisorn socket
  copy:
    src: gunicorn.socket
    dest: /etc/systemd/system/
- name: install gunisorn tmpfile
  copy:
    src: gunicorn.conf
    dest: /etc/tmpfiles.d/
- name: Restart gunicorn
  systemd:
    name: gunicorn
    enabled: yes
    state: restarted
