---
- name: Install pip3
  apt:
    name: python3-pip
    state: present
    force: yes
- name: Copy zold requirements file
  copy:
    src: "{{playbook_dir}}/../requirements.txt"
    dest: "{{project_dir}}/"
# @todo #16 Список модулей requirements слишком велик для продакшина
#  содержит модули для тестирования
- name: Install zold requirements
  pip:
    requirements: "{{project_dir}}/requirements.txt"
    executable: pip3
- name: Copy zold sources
  copy:
    src: "{{playbook_dir}}/../zold"
    dest: "{{project_dir}}/"
    mode: u=rw,g=r,o=r
- name: Copy node sources
  # @todo #40 Необходимо проигнорировать файл config.py,
  #  чтобы каждый деплой не обновлял настройки,
  #  можно сделать для конфиги отдельный модуль и не деплоить его из git
  copy:
    src: "{{playbook_dir}}/../node"
    dest: "{{project_dir}}/"
    mode: u=rw,g=r,o=r
- name: Copy zold settings
  template: "src=roles/zold/templates/config.j2 dest={{project_dir}}/node/config.py"
- name: Project dir permission
  file:
    path: "{{project_dir}}"
    owner: zold
    group: zold
    recurse: yes
    mode: u=rwx,g=rwx,o=rx
